version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_build:
      - llms-txt --docs-dir "$READTHEDOCS_OUTPUT/html"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
